### ISSUE TITLE
NoSuchMethodError: org.jclouds.http.internal.BaseHttpCommandExecutorService

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#1]
Hi @cdancy . I am trying the trivial example in the README.md file, but I get the run time error:

```
1) Error injecting constructor, java.lang.NoSuchMethodError: org.jclouds.http.internal.BaseHttpCommandExecutorService.<init>(Lorg/jclouds/http/HttpUtils;Lorg/jclouds/io/ContentMetadataCodec;Lorg/jclouds/http/handlers/DelegatingRetryHandler;Lorg/jclouds/http/IOExceptionRetryHandler;Lorg/jclouds/http/handlers/DelegatingErrorHandler;Lorg/jclouds/http/internal/HttpWire;)V
  at org.jclouds.http.okhttp.OkHttpCommandExecutorService.<init>(OkHttpCommandExecutorService.java:70)
  while locating org.jclouds.http.okhttp.OkHttpCommandExecutorService
  at com.cdancy.jenkins.rest.config.JenkinsHttpApiModule.configure(JenkinsHttpApiModule.java:47)
  while locating org.jclouds.http.HttpCommandExecutorService
Caused by: java.lang.NoSuchMethodError: org.jclouds.http.internal.BaseHttpCommandExecutorService.<init>(Lorg/jclouds/http/HttpUtils;Lorg/jclouds/io/ContentMetadataCodec;Lorg/jclouds/http/handlers/DelegatingRetryHandler;Lorg/jclouds/http/IOExceptionRetryHandler;Lorg/jclouds/http/handlers/DelegatingErrorHandler;Lorg/jclouds/http/internal/HttpWire;)V
        at org.jclouds.http.okhttp.OkHttpCommandExecutorService.<init>(OkHttpCommandExecutorService.java:70)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.google.inject.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:85)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:405)
        at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:328)
        at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:651)
        at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:643)
        at com.cdancy.jenkins.rest.JenkinsClient.<init>(JenkinsClient.java:35)
        at com.cdancy.jenkins.rest.JenkinsClient$Builder.build(JenkinsClient.java:105)
        at this.is.my.code.main(App.java:24)
```
I suspect it has to do with the http library version. This project builds with:

```
|    |    +--- org.apache.httpcomponents:httpclient:4.3.1
|    |    |    +--- org.apache.httpcomponents:httpcore:4.3
```

And my project builds with:
```
+--- org.eclipse.jgit:org.eclipse.jgit:4.10.0.201712302008-r
|    +--- com.jcraft:jsch:0.1.54
|    +--- com.googlecode.javaewah:JavaEWAH:1.1.6
|    +--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.3
|    |    +--- org.apache.httpcomponents:httpcore:4.4.6
```

I would also like to know the state of this project.

**Comment by cdancy** [comment]
@martinda I haven't touched this project in quite sometime so it's not surprising to me you found a bug. I keep meaning to return to it just haven't had the time these past couple years. I can certainly look into things but admittedly there are not a lot of features here for better or worse.
