### ISSUE TITLE
@Path doesn't support string "{optionalFolderPath}job/{name}/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId={queueId}]"

### ISSUE THREAD

**Issue by hudan15** [cdancy/jenkins-rest#114]
I want to get job's build number through queueId.When I send a request like http://jenkins-server/job/test/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId=52]  on postman,I can get what I need .So I add a api to get result by code.But it doesn't work.I guess it might be some character in the path influence the result.

 The code below works
    @Named("jobs:getBuildNumberByQueueId")
    @Path("{optionalFolderPath}job/{name}/api/xml")
    @Fallback(Fallbacks.NullOnNotFoundOr404.class)
    @Consumes(MediaType.TEXT_PLAIN)
    @GET
    String getBuildNumberByQueueId(@Nullable @PathParam("optionalFolderPath") @ParamParser(OptionalFolderPathParser.class) String optionalFolderPath,@PathParam("name") String jobName,);

The code below doesn't work ,I got null value
    @Named("jobs:getBuildNumberByQueueId")
    @Path("{optionalFolderPath}job/{name}/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId={queueId}]")
    @Fallback(Fallbacks.NullOnNotFoundOr404.class)
    @Consumes(MediaType.TEXT_PLAIN)
    @GET
    String getBuildNumberByQueueId(@Nullable @PathParam("optionalFolderPath") @ParamParser(OptionalFolderPathParser.class) String optionalFolderPath,@PathParam("name") String jobName,@PathParam("queueId") int queueId);

**Comment by cdancy** [comment]
@hudan15 can you recreate on one of the `integTests` in this project? Also ... what is the exception/stacktrace you see?

**Comment by hudan15** [comment]
Thanks for your reply。Here is my test case:
`    public void testGetBuildNumberByQueueId() throws IOException, InterruptedException {
        MockWebServer server = mockWebServer();
        String body = payloadFromResource("/build-xml-tree.xml");

        server.enqueue(new MockResponse().setBody(body).setResponseCode(200));
        JenkinsApi jenkinsApi = api(server.getUrl("/"));
        JobsApi api = jenkinsApi.jobsApi();
        try {
            String success = api.getBuildNumberByQueueId(null,"cecii-wms-1",52);
            assertNotNull(success);
            assertSentAcceptText(server, "GET", "/job/cecii-wms-1/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId=52]");
        } finally {
            jenkinsApi.close();
            server.shutdown();
        }
    }`

build-xml-tree.xml
<build _class="hudson.maven.MavenModuleSetBuild">
    <number>17</number>
    <queueId>52</queueId>
    <result>SUCCESS</result>
</build>

The methods I add like this : 
`   @Named("jobs:getBuildNumberByQueueId")
    @Path("{optionalFolderPath}job/{name}/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId={queueId}]")
    @Fallback(Fallbacks.NullOnNotFoundOr404.class)
    @Consumes(MediaType.TEXT_PLAIN)
    @GET
    String getBuildNumberByQueueId(@Nullable @PathParam("optionalFolderPath") @ParamParser(OptionalFolderPathParser.class) String optionalFolderPath,@PathParam("name") String jobName,@PathParam("queueId") int queueId);`

When I run this tests,the variable "success " got the value of the build-xml-tree.xml,but the assertSentAcceptText() method throw a exception.The completed test results are as follows:
`七月 28, 2020 3:22:31 下午 com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
信息: MockWebServer[51371] starting to accept connections
七月 28, 2020 3:22:32 下午 com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
信息: MockWebServer[51371] received request: GET /job/cecii-wms-1/api/xml%3Ftree=builds%5BqueueId%2Cnumber%2Cresult%5D%26xpath=//build%5BqueueId=52%5D HTTP/1.1 and responded: HTTP/1.1 200 OK
七月 28, 2020 3:22:32 下午 com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
信息: MockWebServer[51371] done accepting connections: socket closed



org.junit.ComparisonFailure: 
Expected :"/job/cecii-wms-1/api/xml?tree=builds[queueId,number,result]&xpath=//build[queueId=52]"
Actual   :"/job/cecii-wms-1/api/xml%3Ftree=builds%5BqueueId%2Cnumber%2Cresult%5D%26xpath=//build%5BqueueId=52%5D"
<Click to see difference>


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.cdancy.jenkins.rest.BaseJenkinsMockTest.assertSentAcceptText(BaseJenkinsMockTest.java:199)
	at com.cdancy.jenkins.rest.features.JobsApiMockTest.testGetBuildNumberByQueueId(JobsApiMockTest.java:917)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)


===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0`

**Comment by cdancy** [comment]
Convo has gone stale and I never had time to go back and look into things. Feel free to re-open should you want to discuss further.
