### ISSUE TITLE
Guava Google Core outdated

### ISSUE THREAD

**Issue by SperlingUnion** [cdancy/jenkins-rest#134]
The Guava dependency from JClouds Components Core need an Update. When i use your dependency i get an NoSuchMethodError. The error appears after i wrote this:
        JenkinsClient client = JenkinsClient.builder().build();
        IntegerResponse queueID = client.api().jobsApi().build(null,"Build");

### Expected Behavior
When i want run this code:
        JenkinsClient client = JenkinsClient.builder().build();
        IntegerResponse queueID = client.api().jobsApi().build(null,"Build");

I expect an Error no Local Server is running or a 403 Bad Request error.

### Current Behavior
When i want run this code:
        JenkinsClient client = JenkinsClient.builder().build();
        IntegerResponse queueID = client.api().jobsApi().build(null,"Build");

With that Dependency:
<dependency>
      <groupId>com.cdancy</groupId>
      <artifactId>jenkins-rest</artifactId>
      <version>0.0.27</version>
</dependency>

I get that Error Message:

Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
	at com.google.inject.TypeLiteral.getSupertype(TypeLiteral.java:238)
	at com.google.inject.spi.InjectionPoint.hierarchyFor(InjectionPoint.java:868)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:656)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:397)
	at com.google.inject.internal.BindingBuilder.toProvider(BindingBuilder.java:118)
	at com.google.inject.internal.BindingBuilder.toProvider(BindingBuilder.java:107)
	at com.google.inject.internal.BindingBuilder.toProvider(BindingBuilder.java:42)
	at com.cdancy.jenkins.rest.config.JenkinsAuthenticationModule.configure(JenkinsAuthenticationModule.java:37)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:405)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:328)
	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:651)
	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:643)
	at com.cdancy.jenkins.rest.JenkinsClient.createApi(JenkinsClient.java:85)
	at com.cdancy.jenkins.rest.JenkinsClient.<init>(JenkinsClient.java:72)
	at com.cdancy.jenkins.rest.JenkinsClient$Builder.build(JenkinsClient.java:220)

### Context
I want to run a Java Based Application that run with the Jenkins Rest API. When i update the Guava Dependency in my pom File i got side effects with the gson Dependency.

### Steps to Reproduce (for bugs)
Start in Intellij Idea a new Maven Project add the dependency from above to the Dependencies. Make a Main Class with a Main Method and run.

### Your Environment
Intellij Idea and Maven i start it in Intellij Idea over Java.

**Comment by martinda** [comment]
Hello @SperlingUnion can you provide which java version you are using please? If you could push a project reproducing the issue to Github, it would help considerably in reproducing the error.

I tried to reproduce the problem with the following code:
```
@Grab("com.cdancy:jenkins-rest:0.0.27")

import com.cdancy.jenkins.rest.JenkinsClient
import com.cdancy.jenkins.rest.domain.common.IntegerResponse

JenkinsClient client = JenkinsClient.builder().build()
IntegerResponse queueID = client.api().jobsApi().build(null,"Build")
```

I use: Groovy Version: 3.0.5 JVM: 11.0.9.1 Vendor: AdoptOpenJDK OS: Linux

And it fails as expected, but I do not get the "java.lang.NoSuchMethodError".

**Comment by SperlingUnion** [comment]
Hello @martinda 

thank you very much for your answer. Also a Happy new Year.

I do not use Groovy in my Project. But i use Java JVM: 1.8 Oracle JDK on Windows. 

Reproduce:
I set my JVM to OpenJDK11 but still get the same error. Do you think its a problem with the Java Version?
Because the package in maven could be to old. But its strange in your test enviremont its working.

**Comment by lucacelenza** [comment]
Hello @SperlingUnion ,
I was able to resolve adding the maven dependency as below (please, note the <classifier> section is mandatory):

```
<dependency>
    <groupId>com.cdancy</groupId>
    <artifactId>jenkins-rest</artifactId>
    <version>0.0.27</version>
    <classifier>all</classifier>
</dependency>
```

**Comment by cdancy** [comment]
Closing. Feel free to re-open should you want to discuss further.
