### ISSUE TITLE
NullPointerException in com.cdancy.jenkins.rest.domain.queue.AutoValue_Task.<init>(AutoValue_Task.java:16)

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#136]
### Current Behavior
When calling:
```
final List<QueueItem> queueItems = client.api().queueApi().queue();
```
This exception is sometimes thrown:
```
Caused by: java.lang.NullPointerException: Null name
        at com.cdancy.jenkins.rest.domain.queue.AutoValue_Task.<init>(AutoValue_Task.java:16)
        at com.cdancy.jenkins.rest.domain.queue.Task.create(Task.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.google.common.reflect.Invokable$MethodInvokable.invokeInternal(Invokable.java:208)
        at com.google.common.reflect.Invokable.invoke(Invokable.java:102)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.newInstance(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:227)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:207)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:275)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:187)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.readAndBuild(NullFilteringTypeAdapterFactories.java:96)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:84)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:63)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:80)
        at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:44)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
        at com.sun.proxy.$Proxy159.queue(Unknown Source)
```

### Context

Without re-trying, it crashes the application. We will implement a retry as a workaround.

### Steps to Reproduce (for bugs)
It seems to be an unexpected response from Jenkins itself. If I get a hold of the HTTP packet that causes it, I will post it here.

### Your Environment

* Version 0.0.27 of jenkins-rest
* Java 11

**Comment by cdancy** [comment]
@martinda interesting ... so `name` is sometimes not present. We can add an `@Nullable` annotation to clean that up easily enough.
