### ISSUE TITLE
NullPointerException in com.cdancy.jenkins.rest.domain.queue.AutoValue_Task.<init>(AutoValue_Task.java:18)

### ISSUE THREAD

**Issue by matthew-bovolotto** [cdancy/jenkins-rest#143]
### Current Behavior
When calling:

`final List<QueueItem> queueItems = client.api().queueApi().queue();`

This exception is sometimes thrown:
```
Caused by: java.lang.NullPointerException: Null url
        at com.cdancy.jenkins.rest.domain.queue.AutoValue_Task.<init>(AutoValue_Task.java:18)
        at com.cdancy.jenkins.rest.domain.queue.Task.create(Task.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.common.reflect.Invokable$MethodInvokable.invokeInternal(Invokable.java:208)
        at com.google.common.reflect.Invokable.invoke(Invokable.java:102)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.newInstance(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:227)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:207)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:275)
        at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:187)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.readAndBuild(NullFilteringTypeAdapterFactories.java:96)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:84)
        at org.jclouds.json.internal.NullFilteringTypeAdapterFactories$IterableTypeAdapter.read(NullFilteringTypeAdapterFactories.java:63)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:80)
        at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:44)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
        at com.sun.proxy.$Proxy136.queue(Unknown Source)
```

### Context
Causes application crash, unable to access queue information.

### Steps to Reproduce (for bugs)
Seems to be inconsistent from Jenkins, captured HTTP packet:

```javascript
 {
    "_class": "hudson.model.Queue",
    "discoverableItems": [],
    "items": [{
            "_class": "hudson.model.Queue$BuildableItem",
            "actions": [],
            "blocked": false,
            "buildable": true,
            "id": 3549,
            "inQueueSince": 1613541614644,
            "params": "",
            "stuck": true,
            "task": {
                "_class": "org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask"
            },
            "url": "queue/item/3549/",
            "why": "There are no nodes with the label [0xe2][0x80][0x98]lsf[0xe2][0x80][0x99]",
            "buildableStartMilliseconds": 1613541614649,
            "pending": false
        }
    ]
}
```

Seems to be the same issue encountered in: https://github.com/cdancy/jenkins-rest/issues/136

### Your Environment
- Version 0.0.28 of jenkins-rest
- Java 11

**Comment by cdancy** [comment]
Interesting .... yeah very similar in that the data being returned is just not complete. Let me spin up a quick fix for this.

**Comment by cdancy** [comment]
Merged. I'll kick a release shortly.

**Comment by cdancy** [comment]
`v0.0.29` has been released.
