### ISSUE TITLE
Deprected headers throw an exception

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#2]
### Expected Behavior
The following code should work against Jenkins 2.107.1:
```groovy
@Grab(group='com.cdancy', module='jenkins-rest', version='0.0.4')
import com.cdancy.jenkins.rest.JenkinsClient 
import com.cdancy.jenkins.rest.domain.system.SystemInfo
JenkinsClient client = JenkinsClient.builder().build();
SystemInfo systemInfo = client.api().systemApi().systemInfo();
```

### Current Behavior
An exception is thrown:
```
Caught: java.lang.NullPointerException: Null hudsonCLIPort
java.lang.NullPointerException: Null hudsonCLIPort
        at com.cdancy.jenkins.rest.domain.system.AutoValue_SystemInfo.<init>(AutoValue_SystemInfo.java:43)
        at com.cdancy.jenkins.rest.domain.system.SystemInfo.create(SystemInfo.java:56)
        at com.cdancy.jenkins.rest.parsers.SystemInfoFromJenkinsHeaders.apply(SystemInfoFromJenkinsHeaders.java:36)
        at com.cdancy.jenkins.rest.parsers.SystemInfoFromJenkinsHeaders.apply(SystemInfoFromJenkinsHeaders.java:31)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy46.systemInfo(Unknown Source)
        at com.cdancy.jenkins.rest.features.SystemApi$systemInfo.call(Unknown Source)
        at t.run(t.groovy:11)
```
### Context
I can't use the jenkins-rest `SystemApi`.

### Steps to Reproduce (for bugs)
Run the above code against Jenkins 2.107.1.

### Your Environment
I have found that between 1.642.4 and 2.107.1, Jenkins no longer sends these headers:
* X-Hudson-CLI-Port
* X-Jenkins-CLI-Port
* X-Jenkins-CLI2-Port
* X-SSH-Endpoint

This looks trivial. I am submitting a PR.

**Comment by cdancy** [comment]
Thanks @martinda! As I noted in the PR: just remove the headers altogether. Not sure how many folks are using this library for older jenkins releases not to mention even care about these headers.
