### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Kneudel** [cdancy/jenkins-rest#246]
Hi,

if I try to create a new JenkisClient object after calling method "...build()" I get this Exception:

`Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: NoSuchMethodError: ConstructorConstructor.<init>(Ljava/util/Map;)V
  at GsonModule.provideGson(GsonModule.java:99)
      \_ installed by: JenkinsHttpApiModule -> GsonModule
  at GsonWrapper.<init>(GsonWrapper.java:38)
      \_ for 1st parameter
  at GsonWrapper.class(GsonWrapper.java:32)
  while locating GsonWrapper
  while locating Json

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: NoSuchMethodError: ConstructorConstructor.<init>(Ljava/util/Map;)V
	at GsonModule.provideGson(GsonModule.java:130)
	at GsonModule$$FastClassByGuice$$2009841.GUICE$TRAMPOLINE(<generated>)
	at GsonModule$$FastClassByGuice$$2009841.apply(<generated>)
	at ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at ProviderMethod.doProvision(ProviderMethod.java:171)
	at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at ContextBuilder.buildInjector(ContextBuilder.java:405)
	at ContextBuilder.buildInjector(ContextBuilder.java:328)
	at ContextBuilder.buildApi(ContextBuilder.java:651)
	at ContextBuilder.buildApi(ContextBuilder.java:643)
	at JenkinsClient.createApi(JenkinsClient.java:85)
	at JenkinsClient.<init>(JenkinsClient.java:72)
	at JenkinsClient$Builder.build(JenkinsClient.java:220)
	at JenkinsAccess.main(JenkinsAccess.java:11)`

**Comment by cdancy** [comment]
@Kneudel I suspect this is most likely due to dependency clobbering. You can use the `all` classifier when resolving this artifact and that should give you better results (at the cost of 1 giant shaded jar). 

Can you give some more details about your setup or what your build looks like?

**Comment by Kneudel** [comment]
Hi,

if I use the all classifier, it works. Thanks.
