### ISSUE TITLE
Empty parameter values cause 

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#26]
### Expected Behavior

When a build parameter is set to the empty string, the QueueItem.create() method should set the parameter value to the empty string.

### Current Behavior

When a build parameter is set to the empty string, the QueueItem.create() method throws an ArrayIndexOutOfBoundsException error:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.cdancy.jenkins.rest.domain.queue.QueueItem.create(QueueItem.java:74)
```
### Context

Some builds are triggered with parameter values set to empty, and those builds cannot be queried by jenkins-rest.

### Steps to Reproduce (for bugs)

The following script reveals the bug:

```groovy
@Grab(group='com.cdancy', module='jenkins-rest', version='0.0.11')

import com.cdancy.jenkins.rest.JenkinsClient
import com.cdancy.jenkins.rest.domain.common.IntegerResponse
import com.cdancy.jenkins.rest.domain.common.RequestStatus
import com.cdancy.jenkins.rest.domain.queue.QueueItem

String config = """
<project> 
  <actions/>
  <properties>
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions>
        <hudson.model.StringParameterDefinition>
          <name>SomeKey1</name>
          <description>whatever1</description>
          <defaultValue>SomeValue1</defaultValue>
        </hudson.model.StringParameterDefinition>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
  </properties>
</project>
"""
// Create a client instance
JenkinsClient client = JenkinsClient.builder().build()

// Create a job
RequestStatus status = client.api().jobsApi().create(null, "myJob", config)

// Setup the parameters
Map<String, List<String>> params = new HashMap<>();
params.put("SomeKey1", [""])

// Submit a build
IntegerResponse queueId = client.api().jobsApi().buildWithParameters(null, "myJob", params)

// Poll the Queue, check for the queue item status
QueueItem queueItem = client.api().queueApi().queueItem(queueId.value())
```

Running that script results in:
```
Jul 14, 2018 10:46:19 AM org.jclouds.logging.jdk.JDKLogger logError
SEVERE: Error parsing input: 1
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.cdancy.jenkins.rest.domain.queue.QueueItem.create(QueueItem.java:71)
...
```
### Your Environment

Linux.

**Comment by martinda** [comment]
PR #27 merged. Closing.

**Comment by martinda** [comment]
@cdancy yes please. Thank you.

**Comment by cdancy** [comment]
@martinda `v0.0.12` has been released.
