### ISSUE TITLE
NoSuchMethodError: 'void ConstructorConstructor.<init>(Map)'

### ISSUE THREAD

**Issue by help-lixin** [cdancy/jenkins-rest#282]
### Your Environment

10) [Guice/ErrorInCustomProvider]: NoSuchMethodError: 'void ConstructorConstructor.<init>(Map)'
  at GsonModule.provideGson(GsonModule.java:99)
      \_ installed by: JenkinsHttpApiModule -> GsonModule
  at GsonWrapper.<init>(GsonWrapper.java:38)
      \_ for 1st parameter
  at GsonWrapper.class(GsonWrapper.java:32)
  while locating GsonWrapper
  at UtilsImpl.<init>(UtilsImpl.java:52)
      \_ for 2nd parameter
  at UtilsImpl.class(UtilsImpl.java:52)
  while locating UtilsImpl
  at ApiContextImpl.<init>(ApiContextImpl.java:48)
      \_ for 4th parameter
  at ApiContextImpl.class(ApiContextImpl.java:48)
  while locating ApiContextImpl<JenkinsApi>

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: NoSuchMethodError: 'void ConstructorConstructor.<init>(Map)'
	at GsonModule.provideGson(GsonModule.java:130)
	at GsonModule$$FastClassByGuice$$1526200.GUICE$TRAMPOLINE(<generated>)
	at GsonModule$$FastClassByGuice$$1526200.apply(<generated>)
	at ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at ProviderMethod.doProvision(ProviderMethod.java:171)
	at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at ContextBuilder.buildInjector(ContextBuilder.java:405)
	at ContextBuilder.buildInjector(ContextBuilder.java:328)
	at ContextBuilder.buildApi(ContextBuilder.java:651)
	at ContextBuilder.buildApi(ContextBuilder.java:643)
	at JenkinsClient.createApi(JenkinsClient.java:85)
	at JenkinsClient.<init>(JenkinsClient.java:72)
	at JenkinsClient$Builder.build(JenkinsClient.java:221)
	at JenkinsConfig.jenkinsClient(JenkinsConfig.java:33)
	at JenkinsConfig$$EnhancerBySpringCGLIB$$a34ed83f.CGLIB$jenkinsClient$6(<generated>)
	at JenkinsConfig$$EnhancerBySpringCGLIB$$a34ed83f$$FastClassBySpringCGLIB$$556372a4.invoke(<generated>)
	at MethodProxy.invokeSuper(MethodProxy.java:244)
	at ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at JenkinsConfig$$EnhancerBySpringCGLIB$$a34ed83f.jenkinsClient(<generated>)
	at java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/Method.invoke(Method.java:577)
	at SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1609)
	at DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
	at DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1462)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1349)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	at AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at InjectionMetadata.inject(InjectionMetadata.java:119)
	at AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at SpringApplication.refresh(SpringApplication.java:734)
	at SpringApplication.refreshContext(SpringApplication.java:408)
	at SpringApplication.run(SpringApplication.java:308)
	at SpringApplication.run(SpringApplication.java:1306)
	at SpringApplication.run(SpringApplication.java:1295)
	at Application.main(Application.java:35)

**Comment by cdancy** [comment]
@help-lixin try using the `all` classifier when requesting this library as that will give you a _shaded_ jar which should get you around this problem.
