### ISSUE TITLE
Crumb issuer errors 

### ISSUE THREAD

**Issue by hcray** [cdancy/jenkins-rest#36]
### Expected Behavior

When the crumb issuer is not configured in Jenkins, launching a enable fails without an error message.

### Current Behavior
.api().jobsApi().enable(null, "DTS");

### Context
   @Test
    public void loginTest() {
        String credentials = Base64Utils.encodeToString("admin:password".getBytes());
        logger.info("credentials :{}", credentials);
        boolean ret = JenkinsClient.builder()
                .endPoint("http://10.6.5.230:8080") // Optional. Defaults to 
                .credentials(credentials)
                .build()
                .api().jobsApi().disable(null, "collect_job_result");
        logger.info("ret: {}", ret);
    }

### Steps to Reproduce (for bugs)
 
 org.jclouds.http.HttpResponseException: Null message connecting to POST 
 http://10.6.5.230:8080/job/collect_job_result/disable HTTP/1.1
	at 
 org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:120)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy271.disable(Unknown Source)
	at com.dahuatech.cicloud.provider.JenkinsRestTest.loginTest(JenkinsRestTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException: Null message
	at com.cdancy.jenkins.rest.domain.common.AutoValue_Error.<init>(AutoValue_Error.java:23)
	at com.cdancy.jenkins.rest.domain.common.Error.create(Error.java:43)
	at com.cdancy.jenkins.rest.fallbacks.JenkinsFallbacks.getErrors(JenkinsFallbacks.java:163)
	at com.cdancy.jenkins.rest.fallbacks.JenkinsFallbacks$CrumbOnError.createOrPropagate(JenkinsFallbacks.java:85)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:94)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy279.crumb(Unknown Source)
	at com.cdancy.jenkins.rest.filters.JenkinsAuthenticationFilter.getCrumb(JenkinsAuthenticationFilter.java:80)
	at com.cdancy.jenkins.rest.filters.JenkinsAuthenticationFilter.filter(JenkinsAuthenticationFilter.java:61)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:90)
	... 35 more

### Your Environment
windows

**Comment by cdancy** [comment]
@hcray is this the latest fix you added to your PR?

**Comment by hcray** [comment]
I fix crumb issuer is configured. Jenkins 2.x is ok.

**Comment by cdancy** [comment]
Lets close this for now, as it seems like folks are able to move forward, and re-open should the need arise.
