### ISSUE TITLE
lang.NoSuchMethodError: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(Lcom/google/gson/internal/ConstructorConstructor;Lcom/google/gson/FieldNamingStrategy;Lcom/google/gson/internal/Excluder;)V

### ISSUE THREAD

**Issue by JianminWu** [cdancy/jenkins-rest#41]
Hi. when I run the hello world.. It doesn't work 
this is the error stack
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(Lcom/google/gson/internal/ConstructorConstructor;Lcom/google/gson/FieldNamingStrategy;Lcom/google/gson/internal/Excluder;)V
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory.<init>(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:118)
	at org.jclouds.json.config.GsonModule.provideGson(GsonModule.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:405)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:328)
	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:651)
	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:643)
	at com.cdancy.jenkins.rest.JenkinsClient.createApi(JenkinsClient.java:83)
	at com.cdancy.jenkins.rest.JenkinsClient.<init>(JenkinsClient.java:70)
	at com.cdancy.jenkins.rest.JenkinsClient$Builder.build(JenkinsClient.java:211)
	at com.cdt.cq.autotest.util.JenkinsUtil.getJenkinsClient(JenkinsUtil.java:25)
	at com.cdt.cq.autotest.util.JenkinsUtil.main(JenkinsUtil.java:30)

 public static JenkinsClient getJenkinsClient() {
        JenkinsClient client = JenkinsClient.builder()
                .endPoint("http://136.3.243.252:8080/") // Optional. Defaults to http://127.0.0.1:8080
                .credentials("root:admin") // Optional.
                .build();
        return client;
    }

    public static void main(String[] args) {
        JenkinsClient client = JenkinsUtil.getJenkinsClient();
        SystemInfo systemInfo = client.api().systemApi().systemInfo();
        System.out.println(systemInfo);
    }

Thanks a lot !!!!!!

**Comment by martinda** [comment]
Hi @JianminWu Look at the solution for #40 , I think this is the same issue.

**Comment by JianminWu** [comment]
Thanks .. This resolve my problem...
